language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script: composer update -v
script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: "timur.shagiakhmetov@corp.badoo.com"
